
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module multiplicador(

	//////////// ADC //////////
	output		          		ADC_CONVST,
	output		          		ADC_SCK,
	output		          		ADC_SDI,
	input 		          		ADC_SDO,

	//////////// ARDUINO //////////
	inout 		    [15:0]		ARDUINO_IO,
	inout 		          		ARDUINO_RESET_N,

	//////////// CLOCK //////////
	input 		          		FPGA_CLK1_50,
	input 		          		FPGA_CLK2_50,
	input 		          		FPGA_CLK3_50,

	//////////// HDMI //////////
	inout 		          		HDMI_I2C_SCL,
	inout 		          		HDMI_I2C_SDA,
	inout 		          		HDMI_I2S,
	inout 		          		HDMI_LRCLK,
	inout 		          		HDMI_MCLK,
	inout 		          		HDMI_SCLK,
	output		          		HDMI_TX_CLK,
	output		          		HDMI_TX_DE,
	output		    [23:0]		HDMI_TX_D,
	output		          		HDMI_TX_HS,
	input 		          		HDMI_TX_INT,
	output		          		HDMI_TX_VS,

	//////////// KEY //////////
	input 		     [1:0]		KEY,

	//////////// LED //////////
	output		     [7:0]		LED,

	//////////// SW //////////
	input 		     [3:0]		SW
);

wire toggle_w;
wire en;
reg [3:0] A;
reg [3:0] B;
wire [7:0] Y;

t_ff tff_sw_inst (
	.clk_i (KEY[0]),
	.rstn_i (1),
	.t_i (1),
	.q_o (toggle_w)
);

t_ff tff_en_inst (
	.clk_i (KEY[1]),
	.rstn_i (1),
	.t_i (1),
	.q_o (en)
);

always @(toggle_w) 
	 begin
        if (toggle_w == 1'b0)
            A <= SW;
        else
            B <= SW;
    end
	 
mult_4bits mult_4bits_inst (
	.clk_i (FPGA_CLK1_50),
	.rst_i (1'b1),
	.en_i (en),
	.A_i (A),
	.B_i (B),
	.Y_o (Y)
);

assign LED = Y;
		
endmodule
