`ifndef CONTROLADOR_RAM_DEFINES_V
`define CONTROLADOR_RAM_DEFINES_V

typedef enum logic [2:0] {
   ST_RAM_IDLE = 3'b000, 
	ST_RAM_READ_NUMBERS,
	ST_RAM_INIT_CALC,
	ST_RAM_WAIT_CALC,
	ST_RAM_STORE_RESULT,
	ST_RAM_END_CALC,
	ST_RAM_WAIT_CONTROL,
	ST_RAM_RESET_STATUS
} estado_ram_t;

`endif
